import { appendRow, filterRows, findById, readTable, softDelete, updateRow } from '../infra/sheets.repository.js';
import { uploadBase64, downloadAsDataUrl, trashFile } from '../infra/drive.repository.js';
import { badRequest, forbidden } from '../core/errors.js';
import { asArray, nowIso, pick, uuid } from '../core/utils.js';
import { getConfig } from './config.module.js';
import { audit } from '../services/audit.service.js';
import { sheetsApi, slidesApi } from '../infra/google.js';

const CATEGORY_CONFIG = [
  {key:'Cámaras',countField:'CantCámaras',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexion','Conexión'],['montaje','Montaje'],['visualizacion','Visualización']]},
  {key:'Puertas',countField:'CantPuertas',questions:[['lector','Lector'],['cerradura','Cerradura'],['funcion','Función'],['contactos','Contactos']]},
  {key:'Servidor',countField:'CantServidores',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexiones','Conexiones'],['servicios','Servicios'],['almacenamiento','Almacenamiento'],['respaldo','Respaldo']]},
  {key:'Grabador',countField:'CantGrabadores',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexiones','Conexiones'],['grabacion','Grabación'],['visualizacion','Visualización'],['almacenamiento','Almacenamiento']]},
  {key:'Bocinas',countField:'CantBocinas',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexion','Conexión'],['montaje','Montaje'],['pruebaSonido','Prueba de sonido']]},
  {key:'Sensor Perimetral',countField:'CantSensoresPerimetrales',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexion','Conexión'],['montaje','Montaje'],['pruebaDeteccion','Prueba de detección']]},
  {key:'Sensor Movimiento',countField:'CantSensoresMovimiento',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexion','Conexión'],['montaje','Montaje'],['pruebaDeteccion','Prueba de movimiento']]},
  {key:'Sensor de Ruptura',countField:'CantSensorRuptura',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexion','Conexión'],['montaje','Montaje'],['pruebaDeteccion','Prueba de ruptura']]},
  {key:'Impresora',countField:'CantImpresora',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexion','Conexión'],['consumibles','Consumibles'],['pruebaImpresion','Prueba de impresión']]},
  {key:'Gabinete',countField:'CantGabinetes',questions:[['limpieza','Limpieza'],['conexiones','Conexiones'],['mediciones','Mediciones'],['respaldo','Respaldo']]},
  {key:'VideoWall',countField:'CantVideoWall',questions:[['limpieza','Limpieza'],['alimentacion','Alimentación'],['conexion','Conexión'],['montaje','Montaje'],['visualizacion','Visualización'],['calibracion','Calibración']]},
];
function maintenancePayload(p, before={}) {
  const counts = p.counts || p.cantidades || (()=>{ try{return JSON.parse(p.CantidadesJSON||'{}')}catch{return{}} })();
  const row={ TituloMantenimiento:pick(p,['TituloMantenimiento','titulo'],before.TituloMantenimiento), ClienteID:pick(p,['ClienteID','ClienteRef','clienteId'],before.ClienteID), Cliente:pick(p,['Cliente','cliente'],before.Cliente), UbicacionID:pick(p,['UbicacionID','ubicacionId'],before.UbicacionID), Ubicacion:pick(p,['Ubicacion','ubicacion'],before.Ubicacion), Estado:pick(p,['Estado','estado'],before.Estado||'PENDIENTE'), Fecha:pick(p,['Fecha','fecha'],before.Fecha), FechaFinalizacion:pick(p,['FechaFinalizacion','fechaFinalizacion'],before.FechaFinalizacion), ResponsableIDsJSON:JSON.stringify(asArray(p.ResponsableIDs||p.responsables||before.ResponsableIDsJSON)), DescripcionGeneral:pick(p,['DescripcionGeneral','descripcion'],before.DescripcionGeneral), CantidadesJSON:JSON.stringify(counts) };
  CATEGORY_CONFIG.forEach((c)=>row[c.countField]=Number(counts[c.countField]??p[c.countField]??before[c.countField]??0)); return row;
}
function devicePayload(p,before={}) {
  let answers=p.respuestas||p.answers||p.RespuestasJSON||before.RespuestasJSON||{};
  if(typeof answers==='string')try{answers=JSON.parse(answers)}catch{answers={}};
  return { UbicacionEquipoID:pick(p,['UbicacionEquipoID','ubicacionEquipoId'],before.UbicacionEquipoID), Zona:pick(p,['Zona','zona'],before.Zona), Categoria:pick(p,['Categoria','categoria','TipoDispositivo'],before.Categoria), NombreDispositivo:pick(p,['NombreDispositivo','nombre'],before.NombreDispositivo), TipoDispositivoID:pick(p,['TipoDispositivoID','tipoDispositivoId'],before.TipoDispositivoID), TipoDispositivo:pick(p,['TipoDispositivo','categoria'],before.TipoDispositivo||before.Categoria), FabricanteID:pick(p,['FabricanteID','fabricanteId'],before.FabricanteID), Fabricante:pick(p,['Fabricante','fabricante'],before.Fabricante), ModeloID:pick(p,['ModeloID','modeloId'],before.ModeloID), Modelo:pick(p,['Modelo','modelo'],before.Modelo), Serie:pick(p,['Serie','serie'],before.Serie), Funcionamiento:pick(p,['Funcionamiento','funcionamiento'],before.Funcionamiento), EnUso:pick(p,['EnUso','enUso'],before.EnUso), Estado:pick(p,['Estado','estado'],before.Estado||'Correcto'), Observacion:pick(p,['Observacion','observacion'],before.Observacion), RespuestasJSON:JSON.stringify(answers), ...Object.fromEntries(Object.entries(answers).map(([k,v])=>[k.charAt(0).toUpperCase()+k.slice(1),v]))};
}
async function enrich(row){
  const devices=(await readTable('Evidencia_Mantenimientos')).filter(d=>String(d.MantenimientoRef)===String(row.MantenimientoID)&&d.Activo!==false);
  const images=await readTable('Mantenimiento imagenes');
  return{mantenimiento:row,responsables:asArray(row.ResponsableIDsJSON).map(UsuarioID=>({UsuarioID})),dispositivos:devices.map(d=>({...d,Imagenes:images.filter(i=>String(i.DispositivoMantenimientoRef)===String(d.EvidenciaMantenimientoID)&&i.Activo!==false).map(i=>({...i,PreviewURL:i.DriveFileID?`https://drive.google.com/thumbnail?id=${encodeURIComponent(i.DriveFileID)}&sz=w1200`:i.DriveURL}))}))};
}
function isAdmin(ctx){return ctx.permissions.includes('USUARIOS_GESTIONAR')||ctx.permissions.includes('MANTENIMIENTOS_ELIMINAR')||ctx.permissions.includes('MANTENIMIENTOS_GESTIONAR');}

export const maintenanceHandlers={
 list:async({payload})=>{let rows=(await readTable('Mantenimiento')).filter(r=>r.Activo!==false);if(payload.dateFrom)rows=rows.filter(r=>String(r.Fecha).slice(0,10)>=String(payload.dateFrom));if(payload.dateTo)rows=rows.filter(r=>String(r.Fecha).slice(0,10)<=String(payload.dateTo));const devices=await readTable('Evidencia_Mantenimientos');rows=rows.map(r=>({...r,DispositivosRegistrados:devices.filter(d=>String(d.MantenimientoRef)===String(r.MantenimientoID)&&d.Activo!==false).length}));return filterRows(rows,payload,['TituloMantenimiento','Cliente','Ubicacion','Responsables','DescripcionGeneral']);},
 get:async({payload})=>enrich(await findById('Mantenimiento',pick(payload,['maintenanceId','MantenimientoID','id']))),
 create:async(ctx)=>{const p=maintenancePayload(ctx.payload);if(!p.TituloMantenimiento||!p.ClienteID)throw badRequest('Título y cliente son obligatorios.');const users=await readTable('Usuarios');const ids=asArray(p.ResponsableIDsJSON);const row={MantenimientoID:uuid(),...p,Responsables:ids.map(id=>users.find(u=>String(u.UsuarioID)===String(id))?.NombreCompleto||id).join(', '),Activo:true,CreadoPor:ctx.user.UsuarioID,FechaCreacion:nowIso(),ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()};await appendRow('Mantenimiento',row);await audit(ctx,'CREAR_MANTENIMIENTO','Mantenimiento',row.MantenimientoID,null,row);return enrich(row);},
 update:async(ctx)=>{const id=pick(ctx.payload,['maintenanceId','MantenimientoID']);const before=await findById('Mantenimiento',id);const p=maintenancePayload(ctx.payload,before);const users=await readTable('Usuarios');p.Responsables=asArray(p.ResponsableIDsJSON).map(uid=>users.find(u=>String(u.UsuarioID)===String(uid))?.NombreCompleto||uid).join(', ');const after=await updateRow('Mantenimiento',id,{...p,ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()});await audit(ctx,'EDITAR_MANTENIMIENTO','Mantenimiento',id,before,after);return enrich(after);},
 finalize:async(ctx)=>{const id=pick(ctx.payload,['maintenanceId','MantenimientoID']);const devices=(await readTable('Evidencia_Mantenimientos')).filter(d=>String(d.MantenimientoRef)===String(id)&&d.Activo!==false);if(!devices.length)throw badRequest('Debe registrar al menos un dispositivo.');return enrich(await updateRow('Mantenimiento',id,{Estado:'FINALIZADO',FechaFinalizacion:nowIso(),ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()}));},
 reopen:async(ctx)=>{if(!isAdmin(ctx))throw forbidden();return enrich(await updateRow('Mantenimiento',pick(ctx.payload,['maintenanceId','MantenimientoID']),{Estado:'PENDIENTE',ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()}));},
 delete:async(ctx)=>{if(!isAdmin(ctx))throw forbidden();return softDelete('Mantenimiento',pick(ctx.payload,['maintenanceId','MantenimientoID']),ctx.user.UsuarioID);},
 deviceCreate:async(ctx)=>{const p=devicePayload(ctx.payload);const mid=pick(ctx.payload,['maintenanceId','MantenimientoID','MantenimientoRef']);if(!mid||!p.Categoria||!p.NombreDispositivo||!p.Zona)throw badRequest('Categoría, nombre y ubicación son obligatorios.');const row={EvidenciaMantenimientoID:uuid(),MantenimientoRef:mid,...p,Activo:true,CreadoPor:ctx.user.UsuarioID,FechaCreacion:nowIso(),ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()};await appendRow('Evidencia_Mantenimientos',row);return row;},
 deviceUpdate:async(ctx)=>{const id=pick(ctx.payload,['deviceId','EvidenciaMantenimientoID']);const before=await findById('Evidencia_Mantenimientos',id);return updateRow('Evidencia_Mantenimientos',id,{...devicePayload(ctx.payload,before),ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()});},
 deviceDelete:async(ctx)=>{if(!isAdmin(ctx))throw forbidden();return softDelete('Evidencia_Mantenimientos',pick(ctx.payload,['deviceId','EvidenciaMantenimientoID']),ctx.user.UsuarioID);},
 imageUpload:async(ctx)=>{const cfg=await getConfig();const file=await uploadBase64({base64:ctx.payload.base64,mimeType:ctx.payload.mimeType||'image/jpeg',fileName:ctx.payload.fileName,folderId:cfg.EVIDENCIAS_FOLDER_ID||cfg.ROOT_FOLDER_ID});const row={FotoDispositivoID:uuid(),DispositivoMantenimientoRef:pick(ctx.payload,['deviceId','DispositivoMantenimientoRef']),Tipo:String(pick(ctx.payload,['Tipo','tipo'],'Antes')).toLowerCase().includes('desp')?'Despues':'Antes',Nombre:file.name,Nota:pick(ctx.payload,['Nota','nota']),MimeType:file.mimeType,Size:file.size||'',DriveFileID:file.id,DriveURL:file.webViewLink,Activo:true,CreadoPor:ctx.user.UsuarioID,FechaCreacion:nowIso(),ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()};await appendRow('Mantenimiento imagenes',row);return{...row,PreviewURL:file.thumbnailLink};},
 imageUpdate:async(ctx)=>updateRow('Mantenimiento imagenes',pick(ctx.payload,['imageId','FotoDispositivoID']),{Tipo:pick(ctx.payload,['Tipo','tipo']),Nota:pick(ctx.payload,['Nota','nota']),ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()}),
 imageDelete:async(ctx)=>{if(!isAdmin(ctx))throw forbidden();const row=await findById('Mantenimiento imagenes',pick(ctx.payload,['imageId','FotoDispositivoID']));await trashFile(row.DriveFileID).catch(()=>{});return softDelete('Mantenimiento imagenes',row.FotoDispositivoID,ctx.user.UsuarioID);},
 mediaGet:async({payload})=>{const row=await findById('Mantenimiento imagenes',pick(payload,['imageId','FotoDispositivoID']));return{FotoDispositivoID:row.FotoDispositivoID,...await downloadAsDataUrl(row.DriveFileID,row.MimeType)};},
 config:async()=>({categories:CATEGORY_CONFIG}),
 spreadsheetReport:async(ctx)=>{if(!isAdmin(ctx))throw forbidden();const data=await enrich(await findById('Mantenimiento',pick(ctx.payload,['maintenanceId','MantenimientoID'])));const created=await sheetsApi.spreadsheets.create({requestBody:{properties:{title:`Mantenimiento DMS - ${data.mantenimiento.Cliente||'Cliente'} - ${String(data.mantenimiento.Fecha).slice(0,10)}`}}});const id=created.data.spreadsheetId;const values=[['REPORTE DE MANTENIMIENTO DMS'],['Título',data.mantenimiento.TituloMantenimiento],['Cliente',data.mantenimiento.Cliente],['Ubicación',data.mantenimiento.Ubicacion],['Fecha',data.mantenimiento.Fecha],[],['Categoría','Nombre','Zona','Fabricante','Modelo','Serie','Funcionamiento','En uso','Estado','Observación'],...data.dispositivos.map(d=>[d.Categoria,d.NombreDispositivo,d.Zona,d.Fabricante,d.Modelo,d.Serie,d.Funcionamiento,d.EnUso,d.Estado,d.Observacion])];await sheetsApi.spreadsheets.values.update({spreadsheetId:id,range:'A1',valueInputOption:'USER_ENTERED',requestBody:{values}});const url=`https://docs.google.com/spreadsheets/d/${id}/edit`;await updateRow('Mantenimiento',data.mantenimiento.MantenimientoID,{SpreadsheetID:id,SpreadsheetURL:url,ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()});return{spreadsheetId:id,spreadsheetUrl:url,excelUrl:`https://docs.google.com/spreadsheets/d/${id}/export?format=xlsx`};},
 slidesReport:async(ctx)=>{if(!isAdmin(ctx))throw forbidden();const data=await enrich(await findById('Mantenimiento',pick(ctx.payload,['maintenanceId','MantenimientoID'])));const created=await slidesApi.presentations.create({requestBody:{title:`Mantenimiento DMS - ${data.mantenimiento.Cliente||'Cliente'}`}});const id=created.data.presentationId;const url=`https://docs.google.com/presentation/d/${id}/edit`;await updateRow('Mantenimiento',data.mantenimiento.MantenimientoID,{SlidesID:id,SlidesURL:url,ActualizadoPor:ctx.user.UsuarioID,FechaActualizacion:nowIso()});return{slidesId:id,slidesUrl:url};},
};
