import React,{useEffect,useMemo,useState}from'react';
import{Link}from'react-router-dom';
import{useAuth}from'../../AuthContext';
import Icon from'../../components/common/Icon';
import{MODULE_ROUTES,normalizeItems,pick,requestAvailable}from'../../services/moduleApi';
function formatDate(value){if(!value)return'Sin fecha';const date=new Date(value);if(Number.isNaN(date.getTime()))return String(value);return new Intl.DateTimeFormat('es-CR',{dateStyle:'medium'}).format(date)}
function getId(row){return String(pick(row,['MantenimientoID','id','RowID'],''))}
export default function MaintenanceListPage(){
 const{sessionToken,hasPermission}=useAuth();
 const canCreate=hasPermission('MANTENIMIENTOS_CREAR')||hasPermission('BOLETAS_CREAR');
 const[records,setRecords]=useState([]),[status,setStatus]=useState('PENDIENTE'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{setRecords(normalizeItems(await requestAvailable(MODULE_ROUTES.maintenance.list,{page:1,pageSize:1000,activo:true},sessionToken)))}catch(err){setError(err.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[sessionToken]);
 const filtered=useMemo(()=>{const query=search.trim().toLowerCase();return records.filter(row=>{const rowStatus=String(pick(row,['Estado'],'PENDIENTE')).toUpperCase();if(rowStatus!==status)return false;if(!query)return true;return[pick(row,['TituloMantenimiento']),pick(row,['Cliente','ClienteRef']),pick(row,['Responsables','Responsable']),pick(row,['DescripcionGeneral'])].join(' ').toLowerCase().includes(query)})},[records,status,search]);
 return <div className="page maintenance-page"><div className="list-page-heading maintenance-heading"><div><span className="eyebrow">Gestión técnica</span><h1>Mantenimientos</h1><p>Inspecciones por dispositivo, evidencias y reportes.</p></div>{canCreate&&<Link className="button button--primary button--compact" to="/mantenimientos/nuevo"><Icon name="add"/>Nuevo</Link>}</div><div className="maintenance-status-tabs" role="tablist"><button type="button" className={status==='PENDIENTE'?'is-active':''} onClick={()=>setStatus('PENDIENTE')}><Icon name="pending_actions"/>Pendientes</button><button type="button" className={status==='FINALIZADO'?'is-active':''} onClick={()=>setStatus('FINALIZADO')}><Icon name="task_alt"/>Finalizados</button></div><label className="knowledge-search maintenance-search"><Icon name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar mantenimiento o cliente..."/><button type="button" className="icon-button" onClick={load} aria-label="Actualizar"><Icon name="refresh"/></button></label>{error&&<div className="alert alert--error"><Icon name="error"/><span>{error}</span></div>}{loading?<div className="state-card state-card--loading"><Icon name="progress_activity"/>Cargando mantenimientos...</div>:<div className="maintenance-grid">{filtered.length?filtered.map(row=>{const id=getId(row),completed=Number(pick(row,['DispositivosRegistrados','CantidadDispositivos'],0)),expected=Number(pick(row,['DispositivosEsperados','CantidadEsperada'],0));return <article className="maintenance-card" key={id}><div className="maintenance-card__top"><span className="maintenance-card__icon"><Icon name="engineering"/></span><span className={`status-chip ${status==='FINALIZADO'?'status-chip--active':'status-chip--pending'}`}>{status}</span></div><div><span className="eyebrow">{pick(row,['Cliente','ClienteRef'],'Sin cliente')}</span><h2>{pick(row,['TituloMantenimiento'],'Mantenimiento sin título')}</h2><p>{pick(row,['DescripcionGeneral'],'Sin descripción general')}</p></div><div className="maintenance-card__meta"><span><Icon name="calendar_month"/>{formatDate(pick(row,['Fecha']))}</span><span><Icon name="groups"/>{pick(row,['Responsables','Responsable'],'Sin responsables')}</span><span><Icon name="location_on"/>{pick(row,['Ubicacion'],'Sin ubicación')}</span></div><div className="maintenance-progress-mini"><div><strong>{completed}</strong><span>registrados</span></div><div><strong>{expected||completed}</strong><span>esperados</span></div></div><Link className="button button--primary" to={`/mantenimientos/${encodeURIComponent(id)}`}>Ver detalle<Icon name="chevron_right"/></Link></article>}):<div className="empty-state"><Icon name="engineering"/><h2>Sin mantenimientos {status==='PENDIENTE'?'pendientes':'finalizados'}</h2><p>No se encontraron registros con los filtros actuales.</p></div>}</div>}</div>
}
