export const TABLES = Object.freeze({
  "Configuracion": { id: "Clave" },
  "Mantenimiento": { id: "MantenimientoID" },
  "Evidencia_Mantenimientos": { id: "EvidenciaMantenimientoID" },
  "Mantenimiento imagenes": { id: "FotoDispositivoID" },
  "KnowledgeCategories": { id: "CategoriaConocimientoID" },
  "KnowledgeArticles": { id: "TutorialID" },
  "KnowledgeAttachments": { id: "AdjuntoID" },
  "TipoDispositivoFabricantes": { id: "RelacionID" },
  "TiposFalla": { id: "TipoFallaID" },
  "Usuarios": { id: "UsuarioID" },
  "Roles": { id: "RolID" },
  "Permisos": { id: "PermisoID" },
  "RolPermisos": { id: "RolPermisoID" },
  "UsuarioPermisos": { id: "UsuarioPermisoID" },
  "Sesiones": { id: "SesionID" },
  "Clientes": { id: "ClienteID" },
  "ClienteUbicaciones": { id: "UbicacionID" },
  "ClienteUbicacionesEquipo": { id: "UbicacionEquipoID" },
  "ClienteContactos": { id: "ContactoID" },
  "Categorias": { id: "CategoriaID" },
  "TiposDispositivo": { id: "TipoDispositivoID" },
  "Fabricantes": { id: "FabricanteID" },
  "Modelos": { id: "ModeloID" },
  "Boletas": { id: "BoletaUID" },
  "BoletaAsignados": { id: "BoletaAsignadoID" },
  "EvidenciasBoleta": { id: "EvidenciaID" },
  "RespuestasBoleta": { id: "RespuestaID" },
  "Consecutivos": { id: "Entidad" },
  "Notificaciones": { id: "NotificacionID" },
  "Auditoria": { id: "AuditoriaID" },
  "Archivos": { id: "ArchivoIDInterno" },
  "EncuestaPreguntas": { id: "PreguntaID" },
  "Encuestas": { id: "EncuestaID" },
  "EncuestaRespuestas": { id: "RespuestaEncuestaID" },
  "KnowledgeArticleCategories": { id: "RelacionArticuloCategoriaID" },
  "FirmaSolicitudes": { id: "SolicitudFirmaID" },
  "FirmaMantenimientoSolicitudes": { id: "SolicitudFirmaMantenimientoID" },
  "TipoDispositivoPreguntas": { id: "PreguntaDispositivoID" },
  "CasosClientes": { id: "CasoID" },
  "CasoEvidencias": { id: "CasoEvidenciaID" },
  "CategoriasCredenciales": { id: "CategoriaCredencialID" },
  "CredencialesClientes": { id: "CredencialID" },
  "IntegracionGateways": { id: "GatewayID" },
  "IntegracionDispositivos": { id: "DispositivoIntegracionID" },
  "IntegracionComandos": { id: "ComandoID" },
  "IntegracionGatewaySecrets": { id: "GatewayID" },
  "KnowledgeArticleContent": { id: "ContenidoParteID" },
  "MaintenanceFinalizationJobs": { id: "JobID" },
  "MaintenanceFinalizationItems": { id: "ItemID" },
  "Agendas": { id: "AgendaID" },
  "AgendaAsignados": { id: "AgendaAsignadoID" },
  "SyncChanges": { id: "ChangeID" },
});

export const DATE_FIELDS = new Set([
  'Fecha','FechaTrabajo','FechaFinalizacion','FechaCreacion','FechaActualizacion','FechaInicio','FechaFin',
  'FechaExpiracion','FechaRevocacion','FechaEnvio','FechaRespuesta','FinalizadaEn','UltimoAcceso','BloqueadoHasta',
  'FechaFirma','FirmaFecha','FechaVisita','FechaProceso','UltimoContacto','UltimaSincronizacionInventario',
  'UltimaConexion','UltimaVerificacion','FechaEntrega','ExpiraEn','FechaAsignacion','FechaDesasignacion',
  'RecordatorioEnviadoEn','ChangedAt','FinalizacionSolicitadaEn','FinalizacionActualizadaEn','FinalizacionProgramadaPara',
  'FinalizacionProgramadaEn','FinalizacionCanceladaEn'
]);
export const TIME_FIELDS = new Set(['HoraInicio','HoraFinal','HoraVisita','HoraFin']);
